apiVersion: v1
kind: Service
metadata:
  labels:
    app: miniblog
  name: miniblog
spec:
  ports:
    - name: https
      protocol: TCP
      port: 8443
      targetPort: 8443
    - name: http
      protocol: TCP
      port: 8081
      targetPort: 8081
    - name: rpc
      protocol: TCP
      port: 9090
      targetPort: 9090
  selector:
    app: miniblog
  sessionAffinity: None
  type: ClusterIP